server:
    port: 8080
spring:
    application:
        name: inventory-information-service

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    datasource:
        url: ${DB_URL:jdbc:mysql://localhost:3306/inventory_db}?createDatabaseIfNotExist=true
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:password}
        driver-class-name: com.mysql.cj.jdbc.Driver

    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 10MB
            max-request-size: 10MB

    output:
        ansi:
            enabled: always

springdoc:
    api-docs:
        path: /v3/api-docs  # default path for openapi json
        enabled: true
    swagger-ui:
        path: /swagger-ui.html  # URL to access Swagger UI (alternative: /swagger-ui/index.html)
logging:
    level:
        org.springdoc: DEBUG       # Logs Swagger/OpenAPI internals
        org.springframework.web: DEBUG  # Logs HTTP request processing
        org.springframework.context: DEBUG  # Logs bean initialization