server:
    port: 8081
spring:
    application:
        name: inventory-information-service

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    datasource:
        url: ${DB_URL:jdbc:mysql://localhost:3306/inventory_db}?createDatabaseIfNotExist=true
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:password}
        driver-class-name: com.mysql.cj.jdbc.Driver

    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 10MB
            max-request-size: 10MB

    output:
        ansi:
            enabled: always

